//! Integration tests for the public pipeline.
//!
//! These build synthetic Terrarium DEM tiles in memory, run them through a
//! `MockTileSource`, and assert end-to-end behavior — most importantly that
//! contours line up across a tile seam, which is the whole reason for the
//! 8-neighbor buffer.

use std::collections::HashMap;
use std::io::Cursor;

use maplibre_contour_rs::config::ThresholdRule;
use maplibre_contour_rs::source::MockTileSource;
use maplibre_contour_rs::tile::{Neighborhood, TileCoord};
use maplibre_contour_rs::{ContourConfig, ContourTiler};

use geozero::mvt::{Message, Tile};
use image::{ImageFormat, Rgba, RgbaImage};

const TILE: u32 = 64;

/// Encode a height (meters) as Terrarium RGB: `h = R*256 + G + B/256 - 32768`.
fn terrarium_rgb(height: f32) -> [u8; 3] {
    let v = (height + 32768.0).clamp(0.0, 65535.999);
    let r = (v / 256.0).floor();
    let g = (v - r * 256.0).floor();
    let b = ((v - r * 256.0 - g) * 256.0).round();
    [r as u8, g as u8, b as u8]
}

/// Build a Terrarium PNG of `TILE`x`TILE` from a height function over the
/// tile's global pixel coordinates, so adjacent tiles share a continuous field.
fn dem_png(tile_x: u32, tile_y: u32, height: impl Fn(f64, f64) -> f32) -> Vec<u8> {
    let mut img = RgbaImage::new(TILE, TILE);
    for py in 0..TILE {
        for px in 0..TILE {
            let gx = (tile_x * TILE + px) as f64;
            let gy = (tile_y * TILE + py) as f64;
            let [r, g, b] = terrarium_rgb(height(gx, gy));
            img.put_pixel(px, py, Rgba([r, g, b, 255]));
        }
    }
    let mut buf = Vec::new();
    img.write_to(&mut Cursor::new(&mut buf), ImageFormat::Png)
        .unwrap();
    buf
}

fn config() -> ContourConfig {
    ContourConfig {
        tile_size: TILE,
        extent: 4096,
        buffer_px: 1,
        smooth: false,
        thresholds: vec![ThresholdRule {
            zoom: 0,
            intervals: vec![50.0, 250.0],
        }],
        ..Default::default()
    }
}

#[test]
fn neighborhood_has_nine_or_fewer_coords() {
    let hood = Neighborhood::around(TileCoord::new(5, 10, 10));
    let coords = hood.coords();
    assert!(coords.len() <= 9);
    assert!(coords.contains(&TileCoord::new(5, 10, 10)));
}

#[test]
fn generates_nonempty_mvt_for_a_sloped_field() {
    // A diagonal ramp guarantees plenty of contour crossings.
    let height = |gx: f64, gy: f64| (gx + gy) as f32;

    let z = 8;
    let center = TileCoord::new(z, 128, 128);
    let hood = Neighborhood::around(center);

    let mut tiles = HashMap::new();
    for c in hood.coords() {
        tiles.insert(c, dem_png(c.x, c.y, height));
    }
    let source = MockTileSource { tiles };

    let tiler = ContourTiler::new(source, config());
    let bytes = tiler.tile(center).unwrap();

    let tile = Tile::decode(&bytes[..]).unwrap();
    assert_eq!(tile.layers.len(), 1);
    assert_eq!(tile.layers[0].name, "contours");
    assert!(!tile.layers[0].features.is_empty());
}

/// The point of the buffer: a contour that crosses the boundary between two
/// adjacent tiles must reach the tile edge in both, at the same place.
#[test]
fn contours_are_continuous_across_a_seam() {
    // Pure north-south ramp: every contour is a horizontal line spanning the
    // full tile width. Reaching the literal east/west edge (x = 0 / extent)
    // only happens because the buffer pulls in the neighbor's margin — without
    // it the line would stop a pixel short. Two horizontally-adjacent tiles
    // over the same field must then expose the same elevations at the seam.
    let height = |_gx: f64, gy: f64| gy as f32;

    let z = 8;
    let left = TileCoord::new(z, 100, 100);
    let right = TileCoord::new(z, 101, 100);

    // Source covering both tiles' neighborhoods.
    let mut tiles = HashMap::new();
    for center in [left, right] {
        for c in Neighborhood::around(center).coords() {
            tiles.entry(c).or_insert_with(|| dem_png(c.x, c.y, height));
        }
    }
    let source = MockTileSource { tiles };
    let tiler = ContourTiler::new(source, config());

    let left_tile = Tile::decode(&tiler.tile(left).unwrap()[..]).unwrap();
    let right_tile = Tile::decode(&tiler.tile(right).unwrap()[..]).unwrap();

    // Elevations present on the left tile's east edge should match those on
    // the right tile's west edge — the seam shares the same contour set.
    let left_eles = edge_elevations(&left_tile, Edge::East);
    let right_eles = edge_elevations(&right_tile, Edge::West);

    assert!(!left_eles.is_empty(), "expected contours touching the seam");
    assert_eq!(
        left_eles, right_eles,
        "contour elevations must match across the shared tile edge"
    );
}

/// A contour tile requested above the DEM's max zoom is generated by sampling
/// the ancestor DEM tile (overzoom), matching maplibre-contour.
#[test]
fn overzooms_above_dem_max_zoom() {
    // Steep diagonal field in z10 pixel space so the small sampled sub-region
    // still spans several contour intervals.
    let height = |gx: f64, gy: f64| (gx + gy) as f32;

    let dem_z = 10u8;
    let req = TileCoord::new(13, 803, 805); // ancestor at z10 is (100, 100)
    let ancestor = TileCoord::new(dem_z, req.x >> 3, req.y >> 3);

    // Provide the z10 DEM around the ancestor; nothing at z11+.
    let mut tiles = HashMap::new();
    for c in Neighborhood::around(ancestor).coords() {
        tiles.insert(c, dem_png(c.x, c.y, height));
    }
    let source = MockTileSource { tiles };

    let cfg = ContourConfig {
        tile_size: TILE,
        extent: 4096,
        buffer_px: 1,
        smooth: false,
        dem_max_zoom: dem_z,
        overzoom: 0,
        thresholds: vec![ThresholdRule {
            zoom: 0,
            intervals: vec![5.0, 25.0],
        }],
        ..Default::default()
    };
    let tiler = ContourTiler::new(source, cfg);

    let tile = Tile::decode(&tiler.tile(req).unwrap()[..]).unwrap();
    assert_eq!(tile.layers[0].name, "contours");
    assert!(
        !tile.layers[0].features.is_empty(),
        "overzoomed tile should still produce contours from the ancestor DEM"
    );
}

enum Edge {
    East,
    West,
}

/// Collect the elevations of contour features that reach the given tile edge
/// (in extent space: west = x≈0, east = x≈extent).
fn edge_elevations(tile: &Tile, edge: Edge) -> Vec<i64> {
    let layer = &tile.layers[0];
    let extent = layer.extent.unwrap_or(4096) as i32;
    let target = match edge {
        Edge::West => 0,
        Edge::East => extent,
    };
    // A small tolerance: rounding can land a pixel off the edge.
    let tol = 2;

    let mut eles = Vec::new();
    for f in &layer.features {
        if feature_touches_x(&f.geometry, target, tol) {
            // tags are [key_idx, val_idx, ...]; key 0 is `ele`.
            if let Some(kv) = f.tags.chunks(2).find(|kv| kv[0] == 0) {
                let v = &layer.values[kv[1] as usize];
                let ele = v
                    .double_value
                    .map(|d| d as i64)
                    .or(v.int_value)
                    .unwrap_or_default();
                eles.push(ele);
            }
        }
    }
    eles.sort_unstable();
    eles.dedup();
    eles
}

/// Decode an MVT line geometry and test whether any segment crosses the
/// vertical line `x == target` (± `tol`). Walking segments (not just vertices)
/// matters because marching-squares vertices land at half-pixel offsets, so a
/// line can cross the tile edge *between* two vertices. Implements the zig-zag
/// command stream from the MVT spec for MoveTo/LineTo.
fn feature_touches_x(geometry: &[u32], target: i32, tol: i32) -> bool {
    let mut i = 0;
    let mut x = 0i32;
    let mut prev_x = 0i32;
    while i < geometry.len() {
        let cmd = geometry[i] & 0x7;
        let count = geometry[i] >> 3;
        i += 1;
        if cmd == 7 {
            continue; // ClosePath: no parameters
        }
        for _ in 0..count {
            let dx = zigzag(geometry[i]);
            i += 2; // skip dx, dy (y is irrelevant for a vertical edge test)
            x += dx;
            if cmd == 2 {
                // LineTo: test the segment [prev_x, x] against the target.
                let (lo, hi) = (prev_x.min(x), prev_x.max(x));
                if target >= lo - tol && target <= hi + tol {
                    return true;
                }
            }
            prev_x = x;
        }
    }
    false
}

#[inline]
fn zigzag(n: u32) -> i32 {
    ((n >> 1) as i32) ^ -((n & 1) as i32)
}
