// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(maplibre_contour_rsFFI)
import maplibre_contour_rsFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_maplibre_contour_rs_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_maplibre_contour_rs_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureMaplibreContourRsInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.
// Magic number for the Rust proxy to call using the same mechanism as every other method,
// to free the callback once it's dropped by Rust.
private let IDX_CALLBACK_FREE: Int32 = 0
// Callback return codes
private let UNIFFI_CALLBACK_SUCCESS: Int32 = 0
private let UNIFFI_CALLBACK_ERROR: Int32 = 1
private let UNIFFI_CALLBACK_UNEXPECTED_ERROR: Int32 = 2

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt8: FfiConverterPrimitive {
    typealias FfiType = UInt8
    typealias SwiftType = UInt8

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt8 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: UInt8, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterFloat: FfiConverterPrimitive {
    typealias FfiType = Float
    typealias SwiftType = Float

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Float {
        return try lift(readFloat(&buf))
    }

    public static func write(_ value: Float, into buf: inout [UInt8]) {
        writeFloat(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}




/**
 * A contour tiler usable from Kotlin/Swift. Thread-safe; share one instance.
 */
public protocol DemManagerProtocol: AnyObject, Sendable {
    
    /**
     * Generate the contour MVT for tile `z/x/y`.
     */
    func tile(z: UInt8, x: UInt32, y: UInt32) throws  -> Data
    
}
/**
 * A contour tiler usable from Kotlin/Swift. Thread-safe; share one instance.
 */
open class DemManager: DemManagerProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_maplibre_contour_rs_fn_clone_demmanager(self.handle, $0) }
    }
    /**
     * Build a tiler from a fetcher and configuration. The DEM URL pattern is
     * taken from `config.dem_url_pattern`.
     */
public convenience init(fetcher: DemTileFetcher, config: ContourConfig) {
    let handle =
        try! rustCall() {
    uniffi_maplibre_contour_rs_fn_constructor_demmanager_new(
        FfiConverterTypeDemTileFetcher_lower(fetcher),
        FfiConverterTypeContourConfig_lower(config),$0
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_maplibre_contour_rs_fn_free_demmanager(handle, $0) }
    }

    

    
    /**
     * Generate the contour MVT for tile `z/x/y`.
     */
open func tile(z: UInt8, x: UInt32, y: UInt32)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeFfiError_lift) {
    uniffi_maplibre_contour_rs_fn_method_demmanager_tile(
            self.uniffiCloneHandle(),
        FfiConverterUInt8.lower(z),
        FfiConverterUInt32.lower(x),
        FfiConverterUInt32.lower(y),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDemManager: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = DemManager

    public static func lift(_ handle: UInt64) throws -> DemManager {
        return DemManager(unsafeFromHandle: handle)
    }

    public static func lower(_ value: DemManager) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DemManager {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: DemManager, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDemManager_lift(_ handle: UInt64) throws -> DemManager {
    return try FfiConverterTypeDemManager.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDemManager_lower(_ value: DemManager) -> UInt64 {
    return FfiConverterTypeDemManager.lower(value)
}






/**
 * Returns the DEM PNG bytes for a tile URL. Implemented on the host side
 * (e.g. an OkHttp call that your interceptor can catch); return `None` for a
 * tile with no data.
 */
public protocol DemTileFetcher: AnyObject, Sendable {
    
    func fetch(url: String) throws  -> Data?
    
}
/**
 * Returns the DEM PNG bytes for a tile URL. Implemented on the host side
 * (e.g. an OkHttp call that your interceptor can catch); return `None` for a
 * tile with no data.
 */
open class DemTileFetcherImpl: DemTileFetcher, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_maplibre_contour_rs_fn_clone_demtilefetcher(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_maplibre_contour_rs_fn_free_demtilefetcher(handle, $0) }
    }

    

    
open func fetch(url: String)throws  -> Data?  {
    return try  FfiConverterOptionData.lift(try rustCallWithError(FfiConverterTypeFfiError_lift) {
    uniffi_maplibre_contour_rs_fn_method_demtilefetcher_fetch(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(url),$0
    )
})
}
    

    
}



// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceDemTileFetcher {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    //
    // Store the vtable directly.
    static let vtable: UniffiVTableCallbackInterfaceDemTileFetcher = UniffiVTableCallbackInterfaceDemTileFetcher(
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            do {
                try FfiConverterTypeDemTileFetcher.handleMap.remove(handle: uniffiHandle)
            } catch {
                print("Uniffi callback interface DemTileFetcher: handle missing in uniffiFree")
            }
        },
        uniffiClone: { (uniffiHandle: UInt64) -> UInt64 in
            do {
                return try FfiConverterTypeDemTileFetcher.handleMap.clone(handle: uniffiHandle)
            } catch {
                fatalError("Uniffi callback interface DemTileFetcher: handle missing in uniffiClone")
            }
        },
        fetch: { (
            uniffiHandle: UInt64,
            url: RustBuffer,
            uniffiOutReturn: UnsafeMutablePointer<RustBuffer>,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> Data? in
                guard let uniffiObj = try? FfiConverterTypeDemTileFetcher.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return try uniffiObj.fetch(
                     url: try FfiConverterString.lift(url)
                )
            }

            
            let writeReturn = { uniffiOutReturn.pointee = FfiConverterOptionData.lower($0) }
            uniffiTraitInterfaceCallWithError(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn,
                lowerError: FfiConverterTypeFfiError_lower
            )
        }
    )

    // Rust stores this pointer for future callback invocations, so it must live
    // for the process lifetime (not just for the init function call).
    static let vtablePtr: UnsafePointer<UniffiVTableCallbackInterfaceDemTileFetcher> = {
        let ptr = UnsafeMutablePointer<UniffiVTableCallbackInterfaceDemTileFetcher>.allocate(capacity: 1)
        ptr.initialize(to: vtable)
        return UnsafePointer(ptr)
    }()
}

private func uniffiCallbackInitDemTileFetcher() {
    uniffi_maplibre_contour_rs_fn_init_callback_vtable_demtilefetcher(UniffiCallbackInterfaceDemTileFetcher.vtablePtr)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDemTileFetcher: FfiConverter {
    fileprivate static let handleMap = UniffiHandleMap<DemTileFetcher>()

    typealias FfiType = UInt64
    typealias SwiftType = DemTileFetcher

    public static func lift(_ handle: UInt64) throws -> DemTileFetcher {
        if ((handle & 1) == 0) {
            // Rust-generated handle, construct a new class that uses the handle to implement the
            // interface
            return DemTileFetcherImpl(unsafeFromHandle: handle)
        } else {
            // Swift-generated handle, get the object from the handle map
            return try handleMap.remove(handle: handle)
        }
    }

    public static func lower(_ value: DemTileFetcher) -> UInt64 {
         if let rustImpl = value as? DemTileFetcherImpl {
             // Rust-implemented object.  Clone the handle and return it
            return rustImpl.uniffiCloneHandle()
         } else {
            // Swift object, generate a new vtable handle and return that.
            return handleMap.insert(obj: value)
         }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DemTileFetcher {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: DemTileFetcher, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDemTileFetcher_lift(_ handle: UInt64) throws -> DemTileFetcher {
    return try FfiConverterTypeDemTileFetcher.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDemTileFetcher_lower(_ value: DemTileFetcher) -> UInt64 {
    return FfiConverterTypeDemTileFetcher.lower(value)
}




/**
 * Everything needed to turn DEM tiles into contour MVT tiles.
 */
public struct ContourConfig: Equatable, Hashable {
    /**
     * DEM pixel encoding.
     */
    public var encoding: Encoding
    /**
     * Output MVT extent (almost always 4096).
     */
    public var extent: UInt32
    /**
     * Buffer, in tile pixels, sampled from neighbors on every edge to keep
     * contours continuous across seams.
     */
    public var bufferPx: UInt32
    /**
     * DEM tile URL template, with `{z}`/`{x}`/`{y}` (and `{-y}` for TMS)
     * placeholders. Used by the FFI fetcher; the URL is what host code (and an
     * HTTP interceptor) sees.
     */
    public var demUrlPattern: String
    /**
     * Highest zoom at which DEM tiles exist. Requests above it are served by
     * overzooming an ancestor tile.
     */
    public var demMaxZoom: UInt8
    /**
     * Extra levels to coarsen the DEM by before sampling: the source tile zoom
     * is `min(z - overzoom, dem_max_zoom)`. 0 = use the exact zoom when present.
     */
    public var overzoom: UInt8
    /**
     * Per-zoom contour spacing rules; the active rule is the highest `zoom`
     * that is `<= requested zoom` (see [`ContourConfig::thresholds_for`]).
     */
    public var thresholds: [ThresholdRule]
    /**
     * Elevation unit scale applied before contouring (1.0 = meters,
     * 3.28084 = feet). Affects threshold matching and the `ele` attribute.
     */
    public var multiplier: Float
    /**
     * Name of the layer written into the MVT.
     */
    public var layerName: String
    /**
     * Attribute key for the elevation value.
     */
    public var elevationKey: String
    /**
     * Attribute key for the major/minor level.
     */
    public var levelKey: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * DEM pixel encoding.
         */encoding: Encoding, 
        /**
         * Output MVT extent (almost always 4096).
         */extent: UInt32, 
        /**
         * Buffer, in tile pixels, sampled from neighbors on every edge to keep
         * contours continuous across seams.
         */bufferPx: UInt32, 
        /**
         * DEM tile URL template, with `{z}`/`{x}`/`{y}` (and `{-y}` for TMS)
         * placeholders. Used by the FFI fetcher; the URL is what host code (and an
         * HTTP interceptor) sees.
         */demUrlPattern: String, 
        /**
         * Highest zoom at which DEM tiles exist. Requests above it are served by
         * overzooming an ancestor tile.
         */demMaxZoom: UInt8, 
        /**
         * Extra levels to coarsen the DEM by before sampling: the source tile zoom
         * is `min(z - overzoom, dem_max_zoom)`. 0 = use the exact zoom when present.
         */overzoom: UInt8, 
        /**
         * Per-zoom contour spacing rules; the active rule is the highest `zoom`
         * that is `<= requested zoom` (see [`ContourConfig::thresholds_for`]).
         */thresholds: [ThresholdRule], 
        /**
         * Elevation unit scale applied before contouring (1.0 = meters,
         * 3.28084 = feet). Affects threshold matching and the `ele` attribute.
         */multiplier: Float, 
        /**
         * Name of the layer written into the MVT.
         */layerName: String, 
        /**
         * Attribute key for the elevation value.
         */elevationKey: String, 
        /**
         * Attribute key for the major/minor level.
         */levelKey: String) {
        self.encoding = encoding
        self.extent = extent
        self.bufferPx = bufferPx
        self.demUrlPattern = demUrlPattern
        self.demMaxZoom = demMaxZoom
        self.overzoom = overzoom
        self.thresholds = thresholds
        self.multiplier = multiplier
        self.layerName = layerName
        self.elevationKey = elevationKey
        self.levelKey = levelKey
    }

    

    
}

#if compiler(>=6)
extension ContourConfig: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeContourConfig: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ContourConfig {
        return
            try ContourConfig(
                encoding: FfiConverterTypeEncoding.read(from: &buf), 
                extent: FfiConverterUInt32.read(from: &buf), 
                bufferPx: FfiConverterUInt32.read(from: &buf), 
                demUrlPattern: FfiConverterString.read(from: &buf), 
                demMaxZoom: FfiConverterUInt8.read(from: &buf), 
                overzoom: FfiConverterUInt8.read(from: &buf), 
                thresholds: FfiConverterSequenceTypeThresholdRule.read(from: &buf), 
                multiplier: FfiConverterFloat.read(from: &buf), 
                layerName: FfiConverterString.read(from: &buf), 
                elevationKey: FfiConverterString.read(from: &buf), 
                levelKey: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: ContourConfig, into buf: inout [UInt8]) {
        FfiConverterTypeEncoding.write(value.encoding, into: &buf)
        FfiConverterUInt32.write(value.extent, into: &buf)
        FfiConverterUInt32.write(value.bufferPx, into: &buf)
        FfiConverterString.write(value.demUrlPattern, into: &buf)
        FfiConverterUInt8.write(value.demMaxZoom, into: &buf)
        FfiConverterUInt8.write(value.overzoom, into: &buf)
        FfiConverterSequenceTypeThresholdRule.write(value.thresholds, into: &buf)
        FfiConverterFloat.write(value.multiplier, into: &buf)
        FfiConverterString.write(value.layerName, into: &buf)
        FfiConverterString.write(value.elevationKey, into: &buf)
        FfiConverterString.write(value.levelKey, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeContourConfig_lift(_ buf: RustBuffer) throws -> ContourConfig {
    return try FfiConverterTypeContourConfig.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeContourConfig_lower(_ value: ContourConfig) -> RustBuffer {
    return FfiConverterTypeContourConfig.lower(value)
}


/**
 * Contour spacing for one zoom level.
 *
 * `intervals[0]` is the minor spacing (lines are traced at every multiple of
 * it). Each further entry is a coarser spacing whose multiples are tagged with
 * a higher `level`: a line's level is the largest index `i` for which its
 * elevation is a multiple of `intervals[i]`. So `[200, 1000]` traces every
 * 200 m and marks every 1000 m as major (`level = 1`).
 */
public struct ThresholdRule: Equatable, Hashable {
    /**
     * Lowest zoom this rule applies to (used by [`ContourConfig::thresholds_for`]).
     */
    public var zoom: UInt8
    /**
     * Contour spacings in meters (pre-`multiplier`), minor first.
     */
    public var intervals: [Float]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Lowest zoom this rule applies to (used by [`ContourConfig::thresholds_for`]).
         */zoom: UInt8, 
        /**
         * Contour spacings in meters (pre-`multiplier`), minor first.
         */intervals: [Float]) {
        self.zoom = zoom
        self.intervals = intervals
    }

    

    
}

#if compiler(>=6)
extension ThresholdRule: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeThresholdRule: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ThresholdRule {
        return
            try ThresholdRule(
                zoom: FfiConverterUInt8.read(from: &buf), 
                intervals: FfiConverterSequenceFloat.read(from: &buf)
        )
    }

    public static func write(_ value: ThresholdRule, into buf: inout [UInt8]) {
        FfiConverterUInt8.write(value.zoom, into: &buf)
        FfiConverterSequenceFloat.write(value.intervals, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeThresholdRule_lift(_ buf: RustBuffer) throws -> ThresholdRule {
    return try FfiConverterTypeThresholdRule.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeThresholdRule_lower(_ value: ThresholdRule) -> RustBuffer {
    return FfiConverterTypeThresholdRule.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * How elevation (meters) is packed into the RGB channels of a DEM tile.
 */

public enum Encoding: Equatable, Hashable {
    
    /**
     * Mapbox Terrain-RGB: `height = -10000 + (R*65536 + G*256 + B) * 0.1`.
     */
    case mapbox
    /**
     * Terrarium (AWS open dataset): `height = R*256 + G + B/256 - 32768`.
     */
    case terrarium





}

#if compiler(>=6)
extension Encoding: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeEncoding: FfiConverterRustBuffer {
    typealias SwiftType = Encoding

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Encoding {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .mapbox
        
        case 2: return .terrarium
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: Encoding, into buf: inout [UInt8]) {
        switch value {
        
        
        case .mapbox:
            writeInt(&buf, Int32(1))
        
        
        case .terrarium:
            writeInt(&buf, Int32(2))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEncoding_lift(_ buf: RustBuffer) throws -> Encoding {
    return try FfiConverterTypeEncoding.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEncoding_lower(_ value: Encoding) -> RustBuffer {
    return FfiConverterTypeEncoding.lower(value)
}



/**
 * Error surfaced across the FFI boundary (flattened to its message).
 */
public enum FfiError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    case Tiler(message: String)
    

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension FfiError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiError: FfiConverterRustBuffer {
    typealias SwiftType = FfiError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Tiler(
            message: try FfiConverterString.read(from: &buf)
        )
        

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FfiError, into buf: inout [UInt8]) {
        switch value {

        

        
        case .Tiler(_ /* message is ignored*/):
            writeInt(&buf, Int32(1))

        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiError_lift(_ buf: RustBuffer) throws -> FfiError {
    return try FfiConverterTypeFfiError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiError_lower(_ value: FfiError) -> RustBuffer {
    return FfiConverterTypeFfiError.lower(value)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionData: FfiConverterRustBuffer {
    typealias SwiftType = Data?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterData.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterData.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceFloat: FfiConverterRustBuffer {
    typealias SwiftType = [Float]

    public static func write(_ value: [Float], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterFloat.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Float] {
        let len: Int32 = try readInt(&buf)
        var seq = [Float]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterFloat.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeThresholdRule: FfiConverterRustBuffer {
    typealias SwiftType = [ThresholdRule]

    public static func write(_ value: [ThresholdRule], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeThresholdRule.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [ThresholdRule] {
        let len: Int32 = try readInt(&buf)
        var seq = [ThresholdRule]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeThresholdRule.read(from: &buf))
        }
        return seq
    }
}
/**
 * A default [`ContourConfig`] (Terrarium, 256 px, 4096 extent) to tweak.
 */
public func defaultConfig() -> ContourConfig  {
    return try!  FfiConverterTypeContourConfig_lift(try! rustCall() {
    uniffi_maplibre_contour_rs_fn_func_default_config($0
    )
})
}
/**
 * Parse maplibre-contour's threshold spec, e.g. `"11*200*1000~12*10*100"`,
 * into per-zoom rules for [`ContourConfig::thresholds`].
 */
public func parseThresholdSpec(spec: String) -> [ThresholdRule]  {
    return try!  FfiConverterSequenceTypeThresholdRule.lift(try! rustCall() {
    uniffi_maplibre_contour_rs_fn_func_parse_threshold_spec(
        FfiConverterString.lower(spec),$0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_maplibre_contour_rs_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_maplibre_contour_rs_checksum_func_default_config() != 58162) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_maplibre_contour_rs_checksum_func_parse_threshold_spec() != 26605) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_maplibre_contour_rs_checksum_method_demmanager_tile() != 46886) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_maplibre_contour_rs_checksum_method_demtilefetcher_fetch() != 9923) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_maplibre_contour_rs_checksum_constructor_demmanager_new() != 10497) {
        return InitializationResult.apiChecksumMismatch
    }

    uniffiCallbackInitDemTileFetcher()
    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureMaplibreContourRsInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all