# ProGuard/R8 rules shipped inside the AAR (as proguard.txt) and applied
# automatically to any app that consumes com.mapeak:contour.
#
# The Kotlin bindings are generated by UniFFI and talk to
# libmaplibre_contour_rs.so through JNA. JNA resolves everything by *name* at
# runtime — native methods via Native.register(), struct fields via the
# @Structure.FieldOrder annotation, callbacks via reflection — so R8 must not
# rename or strip any of it.

# --- Generated UniFFI bindings + public API ---
-keep class com.mapeak.maplibrecontour.** { *; }

# --- JNA ---
# JNA is reflection-heavy: Library/Callback interfaces are proxied, Structure
# subclasses have their fields read by name.
-keep class com.sun.jna.** { *; }
-keepclassmembers class * extends com.sun.jna.Structure { *; }
-keepclassmembers class * implements com.sun.jna.Callback { *; }
-keepclasseswithmembernames class * { native <methods>; }

# JNA is built against the desktop JDK and references classes Android lacks
# (java.awt.*), and pulls in optional pieces that are never reached here.
-dontwarn java.awt.**
-dontwarn com.sun.jna.**

# @Structure.FieldOrder names the fields as strings — keep annotations readable.
-keepattributes *Annotation*, Signature, InnerClasses, EnclosingMethod
